### ISSUE TITLE
Failing due to restructuring of the Debian repo

### ISSUE THREAD

**Issue by vipera66** [mrlesmithjr/ansible-glusterfs#1]
Failed with this error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'http://download.gluster.org/pub/gluster/glusterfs/3.10/LATEST/Debian/stretch/apt stretch Release' does not have a Release file.
fatal: [rpi-k8s-5]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_IajHob/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_IajHob/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 464, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'http://download.gluster.org/pub/gluster/glusterfs/3.10/LATEST/Debian/stretch/apt stretch Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

I checked and that path does not exist on the site.

**Comment by vipera66** [comment]
I am actually using this through your ansible-rpi-k8s-cluster repo. What's the best way to update that? Just delete the directory and clone this repo?

**Comment by mrlesmithjr** [comment]
Sorry about that. These changes are in the [issue#8](https://github.com/mrlesmithjr/ansible-rpi-k8s-cluster/tree/issue%238) branch. You can checkout that branch and should work for GlusterFS. Keep in mind there are some other issues also related to getting K8s cluster up and running as there seems to be some open issues. You can view those [here](https://github.com/mrlesmithjr/ansible-rpi-k8s-cluster/issues/8).
